### ISSUE TITLE
SQLx 0.8.2

### ISSUE THREAD

**Issue by AntoniJakubiak** [SeaQL/sea-query#811] opened 2024-09-04 04:42 UTC
Hi, 

could you please bump SQLx to 0.8.2.
https://github.com/SeaQL/sea-query/blob/1928f238935f6b3d1920838b80236199291b3b30/sea-query-binder/Cargo.toml#L21

There is an important change in SQLx 0.8.2: `u16 => usize` sqlx-postgres/src/message/response.rs
https://github.com/launchbadge/sqlx/commit/53766e4659367e87eeef8a90ef63d5dc91b0e039#diff-47a227e38c95e5ddeaf420a937859c1d1b3872632ed49febf58a26ac429ff569

Kind regards
Antoni Jakubiak

**Comment by billy1624** [comment] 2024-09-05 04:19
Duplicate of https://github.com/SeaQL/sea-query/issues/809

**Closed** 2024-09-05 04:32 UTC

**Comment by billy1624** [comment] 2024-09-05 07:28
Just released https://crates.io/crates/sea-query-binder/0.7.0-rc.2
